# Generated by Django 5.1.3 on 2024-11-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='heading',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_created',
        ),
    ]
